<?php

namespace LilleBitte\Container;

use ReflectionClass;
use LilleBitte\Container\Exception\ContainerException;

use function spl_object_hash;

/**
 * @author Paulus Gandung Prakosa <rvn.plvhx@gmail.com>
 */
class ContainerBuilder extends Container implements ContainerBuilderInterface
{
    /**
     * {@inheritdoc}
     */
    public function register($id, $class)
    {
        return $this->setDefinition($id, new Definition($class));
    }

    /**
     * {@inheritdoc}
     */
    public function autowire($id, $class)
    {
        $definition = new Definition($class);
        $definition->setAutowire(true);

        return $this->setDefinition($id, $definition);
    }

    /**
     * {@inheritdoc}
     */
    public function instance($id, $instance)
    {
        $this->instances[$id] = $instance;
    }

    /**
     * {@inheritdoc}
     */
    public function setDefinition($id, Definition $definition)
    {
        return $this->definitions[$id] = $definition;
    }

    /**
     * {@inheritdoc}
     */
    public function addCompilerPass(CompilerPassInterface $pass)
    {
        $this->compilerPasses[] = $pass;
    }

    /**
     * {@inheritdoc}
     */
    public function compile()
    {
        foreach ($this->compilerPasses as $pass) {
            $pass($this);
        }

        $this->writeCompiledContainerToCache();
    }

    /**
     * {@inheritdoc}
     */
    protected function make($id)
    {
        if (is_null($this->cached) || empty($this->cached)) {
            $this->loadFromCache();
        }

        if (isset($this->cached[$id])) {
            return $this->cached[$id];
        }

        if (isset($this->instances[$id])) {
            return $this->instances[$id];
        }

        $arguments = $this->definitions[$id]->getArguments();
        $class = $this->definitions[$id]->getClass();

        if (!class_exists($class)) {
            throw new ContainerException(
                sprintf(
                    "Class with name (%s) not exists.",
                    $class
                )
            );
        }

        if ($this->definitions[$id]->isAutowired()) {
            return $this->processAutowiring($class);
        }

        if (!count($arguments)) {
            return new $class;
        }

        foreach ($arguments as $key => $argument) {
            if ($argument instanceof Reference) {
                $arguments[$key] = $this->make($argument->getId());
            }
        }

        $refl = new ReflectionClass($class);
        return $refl->newInstanceArgs($arguments);
    }

    /**
     * Write compiled container to cache file.
     *
     * @return void
     */
    protected function writeCompiledContainerToCache()
    {
        $hash = hash_hmac('sha256', spl_object_hash($this), get_class($this));
        $buf  = <<<CACHE_BUFFER
<?php

declare(strict_types=1);

/**
 * This file is generated by Lille Bitte dependency
 * injection container. Do not edit.
 *
 * @Hash {$hash}
 */
CACHE_BUFFER;
        $uses = [];

        $buf   .= "\n";
        $cached = "\n\n\$cachedContainer = [";

        foreach ($this->compilerPasses as $obj) {
            $buf    .= "\nuse " . $obj->getAssociatedClass() . ";";
            $cached .= "\n\t'" . $obj->getTag() . "' => " .
                $obj->getSerializedValue() . ",";
        }

        $buf .= rtrim($cached, ",") . "\n];";
        $buf .= "\n\nreturn \$cachedContainer;\n";

        // write compiled container to {file}
        file_put_contents(
            $this->getCacheDir() . '/container.cache.php',
            $buf
        );
    }

    /**
     * Autowire a service.
     *
     * @param string $class Class name.
     * @return object
     */
    private function processAutowiring($class)
    {
        $refl = new ReflectionClass($class);

        if (!$refl->hasMethod('__construct')) {
            return $refl->newInstanceWithoutConstructor();
        }

        $instances = [];
        $refMethod = $refl->getMethod('__construct');

        foreach ($refMethod->getParameters() as $key => $refParam) {
            $class = $refParam->getClass();

            if (!($class instanceof ReflectionClass)) {
                throw new ContainerException(
                    sprintf(
                        "Parameter (\$%s) is not a class.",
                        $refParam->getName()
                    )
                );
            }

            $instances[] = $this->processAutowiring($class->getName());
        }

        return $refl->newInstanceArgs($instances);
    }
}
